name: secure_audio_player
description: Application audio sécurisée avec biométrie et Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  local_auth: ^3.0.1
  local_auth_android: ^2.0.8
  app_settings: ^7.0.0
  just_audio: ^0.10.5
  audio_service: ^0.18.15
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^1.2.0
  intl: ^0.20.2
  uuid: ^4.5.1
  firebase_storage: ^13.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
