// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGd9o55uWmQIJt6RAeDYrqNpe6JtEv_34',
    appId: '1:827026161843:web:07c6ebc09adf3a1c6370c6',
    messagingSenderId: '827026161843',
    projectId: 'test-ba845',
    authDomain: 'test-ba845.firebaseapp.com',
    storageBucket: 'test-ba845.firebasestorage.app',
    measurementId: 'G-D5EXV0BXQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmg_7-ntySNhytmd-3S4bRMqQLiJ4E0EM',
    appId: '1:827026161843:android:9b190a493304b1106370c6',
    messagingSenderId: '827026161843',
    projectId: 'test-ba845',
    storageBucket: 'test-ba845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlfFXG6yVJxKiw9WKHKcRKZb4D9RAixA',
    appId: '1:827026161843:ios:cccb9124fb445a536370c6',
    messagingSenderId: '827026161843',
    projectId: 'test-ba845',
    storageBucket: 'test-ba845.firebasestorage.app',
    iosBundleId: 'com.secureaudio.player.secureAudioPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlfFXG6yVJxKiw9WKHKcRKZb4D9RAixA',
    appId: '1:827026161843:ios:cccb9124fb445a536370c6',
    messagingSenderId: '827026161843',
    projectId: 'test-ba845',
    storageBucket: 'test-ba845.firebasestorage.app',
    iosBundleId: 'com.secureaudio.player.secureAudioPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGd9o55uWmQIJt6RAeDYrqNpe6JtEv_34',
    appId: '1:827026161843:web:fc4feb7dafb7b8786370c6',
    messagingSenderId: '827026161843',
    projectId: 'test-ba845',
    authDomain: 'test-ba845.firebaseapp.com',
    storageBucket: 'test-ba845.firebasestorage.app',
    measurementId: 'G-4MSGPQF0W7',
  );
}
